name: "Deploy SAM Stack to Production"
on: 
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        architecture: 'x64'
    - name: Telegram deploy start
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        args: The ${{ github.event_name }} event triggered a SAM Deploy with GithubActions.
    - name: set env variable
      run: export v=helloworld
    - name: Run python
      run: python envtest.py
    - name: AWS deploy!
      uses: r0zar/sam-deploy-action@v1.4
      env:
        TEMPLATE: 'template.yml'
        AWS_STACK_NAME: GithubActionsTest
        AWS_REGION: 'us-east-1'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEPLOY_BUCKET: ${{ secrets.AWS_DEPLOY_BUCKET }}
    - name: Telegram deploy finished without problems
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        args: Everything work perfectly, you can be happy and rest.
    - name: Telegram deploy FAIL
      if: ${{ failure() }}
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        args: Something didn't work properly.